<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>NCoreUtils</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>All</AnalysisMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.IO.Abstractions" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">
    <Compile Remove="CodeAnalysis\**" />
    <Compile Remove="CompilerServices\**" />
  </ItemGroup>
</Project>
